### ISSUE TITLE
Implement Mathjax rendering in footer.html partial

### ISSUE THREAD

**Issue by ezragoss** [OberlinMotionLab/HugoSite#1]
Mathjax takes a second to render math, but it allows ML and Tex syntax. It would be awesome to be able to put equations right on a blog post. This is specific to the Osprey theme files as other Hugo themes have equations implements.

For reference, see the [Hugo paper-now implementation](https://github.com/eueung/hugo-paper-now), which we will probably use as a template for any more technical articles that we publish. They has the ability to render complex symbols so it's doable. This is a task best suited for someone comfortable with HTML/CSS/JS

**Comment by ezragoss** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Mathjax Support](https://trello.com/c/ugytGNXl/1-mathjax-support)

**Comment by jamescapuder** [comment]
fixed

**Comment by ezragoss** [comment]
We had to fork the theme repo and start all styling back over

**Comment by ezragoss** [comment]
Refixed
